apiVersion: ENC[AES256_GCM,data:Hrs=,iv:5OZj8xK1wZvYtq3GWK+gR3I9/M4AiriqsAcoGVLjuqw=,tag:GrSEckZJ4HTMNDBXi314Iw==,type:str]
kind: ENC[AES256_GCM,data:p5gWYKX1,iv:IBj3cGH7twpg2El9rmZATmCoJxu5jIK/JfD/KsDi3kg=,tag:RDNaH/ddJ0JN3HJe/rHNEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wkh8/bFj6+uhaJ76bKM=,iv:hOdGJCjVTOrEIAjPIXbF7iMYMmLkBG5Nb8AX8Zup+l4=,tag:BfI9hG5COoYUVbyfUA0hbw==,type:str]
    namespace: ENC[AES256_GCM,data:zu2OE4IJ5w==,iv:nXrhL3qoRUEf9Lc5UnTdCmQRB0pzeNxvLsygwQq4gOs=,tag:3zKlAYQbuy3KnZmlFIWpEQ==,type:str]
type: ENC[AES256_GCM,data:agkCbnFo,iv:URzrYAfx47Mgfp5LeF+m7OilbFgcX5rPPgY9PvfKzvY=,tag:BvtQ+miDuNB194BoeCEv1A==,type:str]
stringData:
    GKEEP_EMAIL: ENC[AES256_GCM,data:La+swXgIKuwdSgkaeJg8BAxswyOfsdqtvYoL,iv:L/b4WiCRe/RRc9Le9a0mVB1LElqH6cDROhKTdTBiE8c=,tag:1l21gM0gjvLnMR7b4e7rQg==,type:str]
    GKEEP_MASTER_TOKEN: ENC[AES256_GCM,data:8mUzaL+zYADMT4cnSYi0QCXxurDaajWHDOLhKrCguOnR42HIzYuEGtSoQ0UrLOBLo1/oxttdiO28woCtaWz1ez8DG3m21+60paNG3d1SBg3FzK3lqrZzbFYsEV2bfnn514DSU4VOEQQCCCZS5g/s1T9DKrTDBL0VddZccCK3BkHjCZfkGjrSmtb/UN+PeI0ehIWjIyZ8d3P/eTkLLVvNOIOqj4wOCFYWbVt9jnRGRNViUel0bcrE2FIEURCJ4ticHYwPrWWSrKWZFnlgwJx0lJNsDXdOYSVKvY1cFVaS9A==,iv:2T1q3+c9hC9XG3TKLC9/qbZbRpg/oabUYU3Wl/VEQMM=,tag:J8vE/c2jzsui+hC3tag2ZA==,type:str]
    GMAIL_APP_PASSWORD: ENC[AES256_GCM,data:TMUg6o25kPg9zG7fCkHAcA==,iv:JkvHtzV97BWriHtBzQjrGHpeoBhPjE0Efk9Z6cIl9pc=,tag:d5CW++4qcYDzERVMv7E3qA==,type:str]
    TODOIST_API_TOKEN: ENC[AES256_GCM,data:4eGU1ibMsRMPg5kZr0x0i7RnjNSCft5v9xuCVYssZ/2wtPBW7JzCGA==,iv:ZgWLc8uRUn9g9JHJeCw/smkhjzN7sf71tLbQ6s6XAQ0=,tag:+kC6qwKXjPga5lNRM7dh6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuajF0NkFEYUttSlRvU3Y1
            VEZmNWpWS1FPdXVwU1A5WTFpbWRMM1RnTDJZCnZ4MUZtbDlvcWRVM1dkOTI2VFIv
            QXVFQi8vdm5ZMXVURGE5VmhhL0pHWkkKLS0tIDlHYlBTUUZIbEFMSVFQWUppNG1y
            MnV6WjJaQVpMbm1LMXJ6aTdKa3pDOU0Ki9D/tHkqqt/gLuMwy7iPnJOwdS3LC2rf
            AooBM/tTubtnCJDBIYTIFanlRcOWKuC3Y/AX5LWIW3hbRzlU/FS/tQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1082k68r6w5gndq8clv4m66dlqletfdcgk64mvcvp45pfaxmal3pq0hghz6
    lastmodified: "2026-08-30T19:15:24Z"
    mac: ENC[AES256_GCM,data:UNno30+T/ATeKIAAKz5blRAYmghWcZ1psZxb16WLIqc8VMKYTmYE0tjCe9CkziGX+MQcf72KPMUapUmpFeAQw6mmKmxz/0D6hI7OIfBFDsaQqpifjITVYUZLPaTMNUzjvff6I12tXT84sQaGYEBx0GHLvYMFUT6fZ3SuZh1vonk=,iv:6eSFqEPxKHrVwvDps9rhV37zkV2ye7wIOXseBbmhooo=,tag:keBkDIw7Mzbq1T1KrTpk3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
