apiVersion: ENC[AES256_GCM,data:Hrs=,iv:5OZj8xK1wZvYtq3GWK+gR3I9/M4AiriqsAcoGVLjuqw=,tag:GrSEckZJ4HTMNDBXi314Iw==,type:str]
kind: ENC[AES256_GCM,data:p5gWYKX1,iv:IBj3cGH7twpg2El9rmZATmCoJxu5jIK/JfD/KsDi3kg=,tag:RDNaH/ddJ0JN3HJe/rHNEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gmCsUp4Xczjmdkl6HJN0tUEG,iv:3TO4luMy1vYskSx/QZRLyPmXXVzab5cJYAoHV5hWRtA=,tag:kgOuJjwVFlyVYot180OQhw==,type:str]
    namespace: ENC[AES256_GCM,data:8h6edxTh,iv:85htyjxa+dfwknPcnsMkg9VxaLy8J5ww0aIx+WhFkY4=,tag:bSGwtgiljGIhl2qjNlJxFw==,type:str]
    labels:
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:jdNyrQaO,iv:kvLPfrM3/1/1CpV5oAWYI/j6OY5i54KgtAkrSQ78BsI=,tag:Xg0vVJFgdz/matzniEKtkw==,type:str]
type: ENC[AES256_GCM,data:agkCbnFo,iv:URzrYAfx47Mgfp5LeF+m7OilbFgcX5rPPgY9PvfKzvY=,tag:BvtQ+miDuNB194BoeCEv1A==,type:str]
stringData:
    GKEEP_EMAIL: ENC[AES256_GCM,data:La+swXgIKuwdSgkaeJg8BAxswyOfsdqtvYoL,iv:L/b4WiCRe/RRc9Le9a0mVB1LElqH6cDROhKTdTBiE8c=,tag:1l21gM0gjvLnMR7b4e7rQg==,type:str]
    GKEEP_MASTER_TOKEN: ENC[AES256_GCM,data:VRFKEbshFXymqjMpU+k5XgCtXSkYCwuCvrEQK/JV7BMqNWGqEKSRbSUuSt7FFVw94V/JDtUG6Kfya8GTZ7s5FRHJJiNilaBJUsP0kHWJb10QErY2yJ5kITVGu5G1HCsMgQjZ+tYOQrWT9mTLkXLHn0dxrMBA9lXREc8zryvod373smBTBSwZzqfJGxyvFeGp2TpRBx4HmDQtnpBlxoTHAoZa5YmzoifWf+H/JWuQDfNQbRDnmiJD7viPSCKE9bchDBaTIsOZVhbtHJDC4Tj3v3WobU05tgYgqeNdfKDuNQ==,iv:IDrX96lc+363OsV9ySib+ZqiKhED8vhBayNn7TtcRGg=,tag:zkwsdm68ngMNs5et4GEu0Q==,type:str]
    GMAIL_APP_PASSWORD: ENC[AES256_GCM,data:uor6TWdKEvhXbpthAJNUhA==,iv:+6rYkEW/R5KO0HOco+oaiWpFmQNfjGyzKIpLAWIx3ZA=,tag:HMBDXmZNu+A83FRaLgWQGA==,type:str]
    TODOIST_API_TOKEN: ENC[AES256_GCM,data:JjgAXqoU6gil3eQFhEO3R9cGmg4C9QXRVN0QU1aaZPT+ye9Ifmb0/Q==,iv:RCgyn3Ov18ZnJnwdJuKEIFnbHjGjX46Ip4I2syVjxyI=,tag:4UTxD01z4EmrKqtaLp9FRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuajF0NkFEYUttSlRvU3Y1
            VEZmNWpWS1FPdXVwU1A5WTFpbWRMM1RnTDJZCnZ4MUZtbDlvcWRVM1dkOTI2VFIv
            QXVFQi8vdm5ZMXVURGE5VmhhL0pHWkkKLS0tIDlHYlBTUUZIbEFMSVFQWUppNG1y
            MnV6WjJaQVpMbm1LMXJ6aTdKa3pDOU0Ki9D/tHkqqt/gLuMwy7iPnJOwdS3LC2rf
            AooBM/tTubtnCJDBIYTIFanlRcOWKuC3Y/AX5LWIW3hbRzlU/FS/tQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1082k68r6w5gndq8clv4m66dlqletfdcgk64mvcvp45pfaxmal3pq0hghz6
    lastmodified: "2026-08-28T07:07:38Z"
    mac: ENC[AES256_GCM,data:8FkvQponlcmjnewrLZYm+fnRTD8dD1BptoefwQ5oltQ5ye1fSlfu6H3svM8fDcli7OMspcnlj2Z5MEHDt8D4Qdi+Qck27EXb+0nb+7tErW1pczaOntJAj16tY7LkvJ9f65oxnpmIr1JYVxisE6EjdeOBGqSgpadJwHzA8i5EJOg=,iv:7/OOW0tBabu5tNuU/mOww4BXHXcv5p0QY84IT7lNW8A=,tag:UN0l9BIT/waEOICKB5808g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
