apiVersion: ENC[AES256_GCM,data:Cis=,iv:qoBj3M8ONYsqnnN1YmP5CvNTO11soCUzRzwl9LCqvKw=,tag:rTrULtvevHmq3SDkc2QKCA==,type:str]
kind: ENC[AES256_GCM,data:Yx/WD/gM,iv:0IlgVm8uMRy4E53YBlyhy5cmd+cBU/zkbcJHqaGgxMU=,tag:+0trrfVD2lpiJ3nLlAnG7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:InkyvdPMLElgimWXpqhgHk/v,iv:vJvAzD3amq/wQaaEzfdrMHK9a34k8BpruRy8zyr+GeI=,tag:uy3kAuuJCWjhh2Xx5yS1yQ==,type:str]
    namespace: ENC[AES256_GCM,data:4C9wQfWr,iv:33xyRk/7BEROROzNPB1QfL36DxSwW6rZCGIU0mf3b8w=,tag:Gam08HJtO3iSbPuHgVk+pA==,type:str]
    labels:
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:kc3ct+6n,iv:kPqbZuVLGa1x1u2V+XAbt4d8zBIyap5Y+7gddZbOQ6g=,tag:XLbmdx5ufp+Rwi8KP/FxVg==,type:str]
type: ENC[AES256_GCM,data:W/ojNDQI,iv:na03ZHEiE5NrPcNgSzDaDgY1otPzZdwIArTgfmTWE2A=,tag:pATScWLzLfAkWOAWRR5nKg==,type:str]
stringData:
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:bXpqO/bMlhnM0NWHTCovESAn3rTYystKa/2Oj1vzRqYi8xXje5iVTMF4z5swHwSbzetiYuXtvYldy9lCY/ZnNA==,iv:8kDi2nZdW31VpLeg/GcH1iDErx2qYmSuiK09nExBGXM=,tag:VEvh4BoLXtuNKWNIbbmZqw==,type:str]
    secret_key: ENC[AES256_GCM,data:FNAzsYAl9u9r79HsAUyolfhAL6l+8i8RGN8rJCXUQ0vhZOTunk1y3s3ZulnCmYpKHeVLFOdzmJvkhlHzDfcg/CQFffU=,iv:EYV3hnRmJ26QNpUdP8Kunyp72aY+rZ5oG1UQjpCWGyQ=,tag:+3+ZRYeD+ivjVWOV9xe/ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaktUS3pPekxNdHFJNjZZ
            YWYrYjI0N0l5RSs1WWE2Ri9JYzFsclM1NUVZCkxUbVJJUDVmVHZDTVBjdmFUWWk4
            YWZaN21SQm9wQ3NSVFllU25sYW5XOGsKLS0tIFJXZnhVVnN5UnJqUEx0RXJCNS9m
            V0JVZ2dlOWtWemFOVzdhRnhneFZoOU0Kr1RCbVKpuqAKyas2D2el63RqTJwYmTKS
            4XVTL0ysAfm4x4o8l8oOhWRBbU0/ViiF5a39ggd3PSv4HbfOKV8NHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1082k68r6w5gndq8clv4m66dlqletfdcgk64mvcvp45pfaxmal3pq0hghz6
    lastmodified: "2026-08-28T07:13:06Z"
    mac: ENC[AES256_GCM,data:qq0SMATsdp+Pp21gaNK7qMc1WUyDXbgEahLQx77HMUKwzQi62I/Z8+k//p3nf0lcHO3BsWV3MFBpy9wD8iPUQz+Za2XDWswFyCotOSJVZIhKG9PoSQy+cnKW/K+p8GyR1UidWUGqqZzog2OdawD2Zxr8A+pKzskcdusNVJGserc=,iv:vy/8iFK3Om7z41hnj/7yFGtBQ6OqGSd/05fbQYF2QSY=,tag:iGr8dn1K5pHtMo983PTxIA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
