---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgBUEQQMBm0OvTzlSlMeL4sloKcSXxhf2HKN/x1wrW1ipZSLBOto+s+GYE2YYSyGIiR5fWKb6viiz6hX+37IDWdFBrtARq2fd3JwMDlMHPYFWVvklf9arEj0VC0THUTWLgq2DCy+zQeLqvkATZuqKVedfooirzaoCMCPGfbHfwUC8rvhvtdpZkM+B41aBpdi61biqKyqRtYIZQDchab7cfuGyvCqJEY/a9GsrN9tpc9mH41st/M2q1lJbM1B0dAmeUQ29+WGVEFuTR+Lhqouny4aJJPbneBY7Bl5+JIZS2Iyu3Vc6H2xCVc6uU7SL7dZ/NAFASI09AF1LjaU+6FDf6k1G2WLixTRLRlNARbYXjPejsBbgHVFQslNQl9+Pe2PfUuC49yFMB4ibI9UA4ZitczpWptxt9IG5MtElKRWfGqjtjmtkGSCwTjjPYGyhONn4UQDDPz59xhHt2Xedtv+m/1EfVeDljQY0a0/K2agj3ypZ1pswJ7+oZ5FcH5LS2eWVNTAcN2sfU3EwA+EE6z3w+ACHZEP8Uj12ZN03fF20WNU6h89ajqYyMeGbJx1lOCm/pBdaeEjkOeSjoBj82XK6PaNSGymd2rjhBiL/A+Nwq4Yc3kLQhQF6EuwXVMWT/AQRv98HW76GAP3orjtIo5cQISO7W0qrn6D57kf35KogFYi3c0ebdBEsF4dVO3JJMrj76Nu4+Xj4yGQzZ3l4F/PMO03UYaxmHPLj4FR0PI1d9OqorLBWdxiIEFkELkEZ5edSGaC8LIo07s3FLVnc6Gpr/4axRW7WncSQwj6DaGHr2YEj8wy77q2LH++sVEUW9ngaHu8B26EPmOtERPaC34qblIWfT49lw9dS4AtxHtFJQi8Xw==
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: argocd
