apiVersion: ENC[AES256_GCM,data:kGE=,iv:o5LVEJxbzLFm8aBWSKpRwyZVFGzgrWaPvz1o1FvywDA=,tag:HPWlAa0lmHa7xM1Y2SPy2g==,type:str]
kind: ENC[AES256_GCM,data:4e4d1t6X,iv:J5WAwSIWujx2/v4tOT/YMbcpduOxKz3f1lq6cWc2I2w=,tag:V3T0AH5bwGomNCCVrG1xhw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UWDYX8x3Om8qmDc1HjYtpNUd,iv:+GCd/C0oEQEKUhD19kP5Az26c1NvacPYkmFq4wUd/TM=,tag:KGFnwLHcPtpWqGrccO7nvw==,type:str]
    namespace: ENC[AES256_GCM,data:hqjWwrvr,iv:pjsUguxKeNQuw/kf2pKXKAAbhEOzft5k6V0g2U/gswk=,tag:kxegMqNuKNK1pSXU8F5bDA==,type:str]
    labels:
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:GhlRMTmi,iv:+92d6skdDwCSl+MRETRu9JLTFUvU/PoeKqzvpfWk0r4=,tag:bKMo/KLh27h/rDf7qA1tZw==,type:str]
type: ENC[AES256_GCM,data:HNPqU3LQ,iv:uzZbEXOFLtr5h8J4pyN7EIEeriKj9hcO47AqPpY+iNc=,tag:tAhbaWqbzBCunZaT5A+Niw==,type:str]
stringData:
    oidc.authentik.clientSecret: ENC[AES256_GCM,data:qfIWo8ZBZlGNUHtQTOdx7ZT3XxJRijMtFtUMgAVfjj/ER5l5RG0qa4YS+BMAVQiRNiMCti7hIBebRq9Eu75++/25WzlTaJvROYphQc7N7cGawsrdRtX4uXTMfbdAGCcY1kQIPadcFNXmgdGIIoqZaNQk9MojE2ThwyxBdxqNHsk=,iv:CzzBF295fTbQr6AyiBI4lAmM0BYybkiUz22/U0evj54=,tag:ZVETF4NpE7QRI1EPBQoZ2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdm01TEc5NXZ5T3QyeWhi
            NnpwSGFodmRzdEo4d3VrZlFpVTJ3R1RpTWljCnBLbm9NdFpIbllTMXhHZEdOS3FO
            MlkzQW5FeXIrenVDOVhmZFUrZUd5NVUKLS0tIFgxVHd2dnBpSHVEYktaVHFLQ0pQ
            aFFzbjlYNFFIcm5YSHd1RFdlRm5mRUUKWSkt3ekZkRMtTtqco1ybNamG2iZYzhmF
            VrYMJTYh8bcW3Pp93AhMJ+HVUxWnyt+tR0BmdiJD2arApAB4ZPNdAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1082k68r6w5gndq8clv4m66dlqletfdcgk64mvcvp45pfaxmal3pq0hghz6
    lastmodified: "2026-08-26T16:46:06Z"
    mac: ENC[AES256_GCM,data:PtaqiOwq4rbs5LFtpNkLpCVe9zkkh9Xoh+SywpaGtXlSrWeFALuJRHCv870s+Vk2KqY+V4h8nyHanrXCJOt9knjGuvzhYdCuI7TNNtww/sYpgBa7E+0zztWawB06gjy1nc2ks7dDoztl597DLAsVXDGUuE/jFlHrFLVjbTbLK/E=,iv:raP6P6Eg4yUZ2zLFFi4KYFrSnbrTRia2zwKV0MDiQRM=,tag:rUN7k0X1ZF4OSCJaKWooYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
