apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wireguard-system

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - wireguard-metrics-service.yaml
  - monitoring.yaml
