---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-secret
  namespace: wireguard-system
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgAZEvGVQLIG2+Db5LjwmirnjIzLG5cbgRAMQm+N4CELUXFPiN+2pYijG2sSfMT4H53Dunk8tNPU6o/q6rnyLbmpYFd3CN2PrBaoOstgkBBJAlkJqU7zFvzTNQv8gU7W/DzJhsEoCzRsK9aTtOXZr37RMatxSHmyR/VI2zuJ+chok6xlm+SdzTzU6Ga+nTula05DjMcr8xofNs9dRhKd+1tS+jnqk1BO8OdnyYmTLPBVAn3q08MVJ8DbjtWiI2lzr7CJF2rU/T4Gq6R7b86bJgwGbl5FAs08atruFn7pXmbqa5EQYfyf5DgFOdJvmmriDLXH3A7WsjzHkYmpIX4AjrEeB1lJn2fwxVyAj/6UvWhFbGV8THyqhgi4wvq6HtXhPUhISyYxZimrkr0cl4T+FEMHmO0RHdVvtbKCEqpFArLC1V0+7fjei1/hInFMfOOojduwUyVUkByy3JMlu6rveN3YqFna0wbF3ZNpQ/5cfXLHjKjQjG2pGqD7z2JSinY0G8R+YV8UVCTebHB31uG3ve1sSkh9SS6zRH4MJgW0CtRqu//NpXVgtx4KBzTMtYDGRWi1MkSQsyoEL4UMkjnpoL3iY4KQpdpxWCGrV23XTs0V+sdh7xcfdV0tSjVp+a35QutDG80zE7V8TFoYrS7ki42xQD1Z/3201/lyz+rndATJBwUPbcc4eCsBxqxj7mgYgqV4cNKV2G8Aaf5Z24zjab9c7Y11+Rq3V10cCsknUuU7n9UrMDSaQn91sEDvNWs=
  template:
    metadata:
      name: wireguard-secret
      namespace: wireguard-system
