apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.203
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: wireguard
  ports:
    - port: 51820
      targetPort: 51820
      protocol: UDP
      name: wireguard-udp
