apiVersion: v1
kind: Namespace
metadata:
  name: dns-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf-pvc
  namespace: dns-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 64Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work-pvc
  namespace: dns-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: dns-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
        - name: adguard
          image: adguard/adguardhome:latest
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 80
              name: web-http
            - containerPort: 3000
              name: setup-http
          volumeMounts:
            - name: adguard-conf
              mountPath: /opt/adguardhome/conf
            - name: adguard-work
              mountPath: /opt/adguardhome/work
      volumes:
        - name: adguard-conf
          persistentVolumeClaim:
            claimName: adguard-conf-pvc
        - name: adguard-work
          persistentVolumeClaim:
            claimName: adguard-work-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  namespace: dns-system
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.201
  clusterIP: 10.43.6.74
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 80
      targetPort: 80
      name: web-http
    - port: 3000
      targetPort: 3000
      name: setup-http
  selector:
    app: adguard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-ingress
  namespace: dns-system
spec:
  rules:
    - host: adguard.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard-dns
                port:
                  name: web-http