apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work-pvc
  namespace: dns-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
