apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-tls-cert
  namespace: kube-system
spec:
  secretName: homelab-tls
  commonName: "*.home"
  dnsNames:
    - "*.home"
    - "*.dc.home"
    - "dc.home"
  issuerRef:
    name: home-ca-issuer
    kind: ClusterIssuer
