apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certs
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://charts.jetstack.io'
      targetRevision: v1.15.3
      chart: cert-manager
      helm:
        values: |
          installCRDs: true
    - repoURL: 'https://github.com/DanielCraciunGitHub/homelab.git'
      targetRevision: HEAD
      path: infrastructure/certs
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
