apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DanielCraciunGitHub/homelab.git'
    targetRevision: HEAD
    path: infrastructure/cnpg
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cnpg-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
