apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluetooth-panel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DanielCraciunGitHub/homelab.git'
    targetRevision: HEAD
    path: apps/bluetooth-panel
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bluetooth-panel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
